"""Knowledge, evidence, memory and decision models plus the trust rules (master plan 6.12-6.13)."""

from __future__ import annotations

import hashlib
import uuid
from datetime import datetime
from enum import StrEnum
from typing import Any, Self

from pydantic import BaseModel, ConfigDict, Field, model_validator

from eios_domain.ids import new_id, utcnow
from eios_domain.vault import Vault, check_vault_invariants


class Trust(StrEnum):
    RAW = "RAW"
    OBSERVED = "OBSERVED"
    DERIVED = "DERIVED"
    VERIFIED = "VERIFIED"
    APPROVED = "APPROVED"

    @property
    def rank(self) -> int:
        return list(Trust).index(self)

    def __lt__(self, other: object) -> bool:
        return isinstance(other, Trust) and self.rank < other.rank

    def __le__(self, other: object) -> bool:
        return isinstance(other, Trust) and self.rank <= other.rank


class Health(StrEnum):
    CURRENT = "CURRENT"
    UNVERIFIED = "UNVERIFIED"
    STALE = "STALE"
    CONTRADICTED = "CONTRADICTED"
    SUPERSEDED = "SUPERSEDED"
    HISTORICAL = "HISTORICAL"
    QUARANTINED = "QUARANTINED"


class SourceKind(StrEnum):
    MANUAL = "manual"  # typed by a human
    TOOL = "tool"  # output of a tool/adapter
    LLM = "llm"  # generated by a model
    CODE = "code"  # extracted by a deterministic parser from source
    RESEARCH = "research"  # public/web research
    IMPORT = "import"  # imported package


# Highest trust a record may be *created* with, by source. Anything higher has to be earned
# through the evidence pipeline and verification (Phase 9). Raw tool output and LLM assertions
# can never be created as VERIFIED/APPROVED.
TRUST_CEILING: dict[SourceKind, Trust] = {
    SourceKind.MANUAL: Trust.APPROVED,
    SourceKind.CODE: Trust.DERIVED,
    SourceKind.IMPORT: Trust.DERIVED,
    SourceKind.TOOL: Trust.OBSERVED,
    SourceKind.RESEARCH: Trust.OBSERVED,
    SourceKind.LLM: Trust.OBSERVED,
}
PIPELINE_CEILING = Trust.DERIVED  # knowledge created from an evidence-backed finding


class TrustViolationError(ValueError):
    """A trust level was claimed that the source or pipeline does not justify."""


class ProvenanceInput(BaseModel):
    model_config = ConfigDict(frozen=True)

    source: str = Field(min_length=1, max_length=500, description="file, URL, tool id, ...")
    source_version: str | None = Field(default=None, max_length=200, description="e.g. commit")
    actor: str = Field(min_length=1, max_length=200, description="model, tool or human")
    evidence_id: uuid.UUID | None = None
    evidence_hash: str | None = Field(default=None, max_length=128)
    notes: str = ""


class KnowledgeItemCreate(BaseModel):
    model_config = ConfigDict(frozen=True)

    vault: Vault
    project_id: uuid.UUID | None = None
    kind: str = Field(default="note", min_length=1, max_length=60)
    title: str = Field(min_length=1, max_length=300)
    content: str = Field(min_length=1, max_length=200_000)
    tags: list[str] = Field(default_factory=list, max_length=50)
    trust: Trust = Trust.RAW
    health: Health = Health.UNVERIFIED
    confidence: float = Field(default=0.5, ge=0, le=1)
    source_kind: SourceKind
    created_by: str = Field(min_length=1, max_length=200)
    expires_at: datetime | None = None
    subject_key: str | None = Field(default=None, max_length=300)
    limitations: str = ""
    version_ref: str | None = Field(default=None, max_length=200)
    metadata: dict[str, Any] = Field(default_factory=dict)
    provenance: list[ProvenanceInput] = Field(default_factory=list)
    from_pipeline: bool = Field(
        default=False, description="created from an evidence-backed finding (raises the ceiling)"
    )

    @model_validator(mode="after")
    def _invariants(self) -> Self:
        check_vault_invariants(self.vault, project_id=self.project_id, expires_at=self.expires_at)
        ceiling = (
            PIPELINE_CEILING
            if self.from_pipeline and self.source_kind is not SourceKind.MANUAL
            else TRUST_CEILING[self.source_kind]
        )
        if not self.trust <= ceiling:
            raise TrustViolationError(
                f"{self.source_kind.value} knowledge cannot be created with trust "
                f"{self.trust.value} (ceiling {ceiling.value})"
            )
        if self.source_kind is not SourceKind.MANUAL and not self.provenance:
            raise TrustViolationError("non-manual knowledge requires provenance")
        if self.health is Health.CURRENT and self.trust <= Trust.RAW:
            raise TrustViolationError("RAW knowledge cannot be marked CURRENT")
        return self


class KnowledgeItem(BaseModel):
    model_config = ConfigDict(frozen=True)

    id: uuid.UUID
    vault: Vault
    project_id: uuid.UUID | None
    kind: str
    title: str
    content: str
    tags: list[str]
    trust: Trust
    health: Health
    confidence: float
    source_kind: SourceKind
    created_by: str
    created_at: datetime
    updated_at: datetime
    expires_at: datetime | None
    subject_key: str | None
    limitations: str
    version_ref: str | None
    superseded_by: uuid.UUID | None
    metadata: dict[str, Any]


class EvidenceCreate(BaseModel):
    model_config = ConfigDict(frozen=True)

    vault: Vault = Vault.EPHEMERAL
    project_id: uuid.UUID | None = None
    run_id: uuid.UUID | None = None
    source_kind: SourceKind = SourceKind.TOOL
    tool_id: str | None = Field(default=None, max_length=200)
    summary: str = Field(default="", max_length=1000)
    media_type: str = Field(default="text/plain", max_length=100)
    expires_at: datetime | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)

    @model_validator(mode="after")
    def _invariants(self) -> Self:
        check_vault_invariants(self.vault, project_id=self.project_id, expires_at=self.expires_at)
        return self


class EvidenceRecord(BaseModel):
    """Raw evidence is always RAW trust: it is what was observed, not what is believed."""

    model_config = ConfigDict(frozen=True)

    id: uuid.UUID
    vault: Vault
    project_id: uuid.UUID | None
    run_id: uuid.UUID | None
    source_kind: SourceKind
    tool_id: str | None
    summary: str
    media_type: str
    content_hash: str
    size_bytes: int
    blob_id: uuid.UUID | None
    created_at: datetime
    expires_at: datetime | None
    trust: Trust = Trust.RAW


class Observation(BaseModel):
    model_config = ConfigDict(frozen=True)

    id: uuid.UUID
    evidence_id: uuid.UUID
    statement: str
    confidence: float
    created_by: str
    created_at: datetime


class Finding(BaseModel):
    model_config = ConfigDict(frozen=True)

    id: uuid.UUID
    observation_ids: list[uuid.UUID]
    statement: str
    confidence: float
    limitations: str
    created_by: str
    created_at: datetime


class MemoryCreate(BaseModel):
    model_config = ConfigDict(frozen=True)

    vault: Vault
    project_id: uuid.UUID | None = None
    scope: str = Field(default="project", pattern="^(user|project|session)$")
    content: str = Field(min_length=1, max_length=20_000)
    tags: list[str] = Field(default_factory=list, max_length=50)
    importance: float = Field(default=0.5, ge=0, le=1)
    expires_at: datetime | None = None
    created_by: str = Field(min_length=1, max_length=200)

    @model_validator(mode="after")
    def _invariants(self) -> Self:
        check_vault_invariants(self.vault, project_id=self.project_id, expires_at=self.expires_at)
        return self


class DecisionStatus(StrEnum):
    PROPOSED = "proposed"
    ACCEPTED = "accepted"
    REJECTED = "rejected"
    SUPERSEDED = "superseded"


class DecisionCreate(BaseModel):
    model_config = ConfigDict(frozen=True)

    vault: Vault = Vault.PROJECT
    project_id: uuid.UUID | None = None
    question: str = Field(min_length=1, max_length=2000)
    alternatives: list[dict[str, Any]] = Field(default_factory=list)
    selected: str = Field(default="", max_length=2000)
    rationale: str = Field(default="", max_length=20_000)
    evidence_ids: list[uuid.UUID] = Field(default_factory=list)
    decider: str = Field(min_length=1, max_length=200)
    reviewers: list[str] = Field(default_factory=list)
    status: DecisionStatus = DecisionStatus.PROPOSED

    @model_validator(mode="after")
    def _invariants(self) -> Self:
        if self.vault is Vault.EPHEMERAL:
            raise ValueError("decisions are durable and cannot live in the ephemeral vault")
        check_vault_invariants(self.vault, project_id=self.project_id, expires_at=None)
        return self


class Decision(BaseModel):
    model_config = ConfigDict(frozen=True)

    id: uuid.UUID
    vault: Vault
    project_id: uuid.UUID | None
    question: str
    alternatives: list[dict[str, Any]]
    selected: str
    rationale: str
    evidence_ids: list[uuid.UUID]
    decider: str
    reviewers: list[str]
    status: DecisionStatus
    superseded_by: uuid.UUID | None
    created_at: datetime
    updated_at: datetime


class HumanApproval(BaseModel):
    """Proof that a human decided something. Constructed only by the admin-authenticated surface."""

    model_config = ConfigDict(frozen=True)

    approval_id: uuid.UUID = Field(default_factory=new_id)
    approver: str = Field(min_length=1, max_length=200)
    scope: str = Field(min_length=1, max_length=200)
    reason: str = ""
    approved_at: datetime = Field(default_factory=utcnow)


def content_hash(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()
